[package]
name = "fruit_classifier"
version = "0.1.0"
edition = "2024"

[lib]
name = "fruit_classifier"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15"
rand = "0.8"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
plotters = "0.3.5"